# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  branches:
    include:
    - main
  paths:
    include:
    - GivHub-Angular

pool:
  vmImage: ubuntu-latest

variables:
  appDir: GivHub-Angular

steps:

# - task: SonarCloudPrepare@1
#   inputs:
#     SonarCloud: 'sonarcloudFront'
#     organization: '210215-usf-net'
#     scannerMode: 'CLI'
#     configMode: 'manual'
#     cliProjectKey: '210215-USF-NET_GivHub-By-SHRKD-Angular'
#     cliProjectName: 'GivHub-By-SHRKD-Angular'
#     cliSources: '$(appDir)/src'
#     extraProperties: |
#       sonar.coverage.exclusions=**/GivHub-Angular/*.spec.ts

# - task: DotNetCoreCLI@2
#   inputs:
#     command: 'test'
#     projects: '**SHRKD_GivHub/GivHubTests/*.csproj'
#     arguments: --configuration $(buildConfiguration) --collect "Code Coverage"


- task: NodeTool@0
  inputs:
    versionSpec: '14.x'
  displayName: 'Install Node.js'

- script: npm ci
  displayName: npm install
  workingDirectory: $(appDir)

- script: npx ng build --prod
  displayName: ng build
  workingDirectory: $(appDir)
  
# - task: SonarCloudAnalyze@1
# - task: SonarCloudPublish@1
#   inputs:
#     pollingTimeoutSec: '300'

- task: AzureWebApp@1
  inputs:
    azureSubscription: 'Azure subscription 1(583825bd-d55a-497c-bfe6-2e3972e128e2)'
    appType: 'webAppLinux'
    #appName: 'GivHub'
    appName: 'GivHub'
    package: '$(appDir)/dist'
